### ISSUE TITLE
Fade transitions

### ISSUE THREAD

**Issue by k3vob** [AlvinJian/auto_background_changer#3]
Not an issue, but is there any way (possibly with compton or another compositor) to add fading transitions when the wallpaper changes. I find it very harsh and unsubtle how the transitions are instantaneous as is.

Great project though, works perfectly otherwise!

**Comment by AlvinJian** [comment]
which script(backend) you used to change the wallpaper? The effect on changing wallpaper depends on the backend script, not the main program. In fact, the main program(python codes) is just a schedular calling the backend script to change wallpaper. :P

**Comment by k3vob** [comment]
I am using feh as the backend in i3 and have compton as my compositor - any idea how I can have the transitions be a subtle fade?

**Comment by AlvinJian** [comment]
I have no idea how to do it on i3. I also used i3 but without any compositor, and I never thought of using transition. Can't help ya, sorry~~

UPDATE: Perhaps you can try imagemagick to do transition manually. $HOME/.fehbg records the path of your current wallpaper and $1 in the backend script is the wallpaper to be set, so you have to convert these two images step by setp to create transition.
