### ISSUE TITLE
Corrupt <autobgch> package.

### ISSUE THREAD

**Issue by pandevim** [AlvinJian/auto_background_changer#4]
Package present in repository but gives installation error for `yay` (AUR-helper).  
@AlvinJian 
```bash
~]$ yay -Ss autobgch
   aur/python-autobgch 0.4-4 (+1 0.00%) 
   A simple and automatic wallpaper changer supporting various backends for Linux

```
```bash
~]$ yay -S autobgch
==> Error: Could not find all required packages:
    autobgch (Target)

```

**Comment by AlvinJian** [comment]
In AUR, my package is called [python-autobgch](https://aur.archlinux.org/packages/python-autobgch/). I believe you have to specify full package name to install it.
